name: "validation and testing"

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  validate:
    name: validate
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate
        run: |
          set -e
          
          rootModules=$(find examples  -name main.tf | sed 's:[^/]*$::')
          
          for rootModule in ${rootModules}; do
            printf "\n\nValidating root module %s\n" ${rootModule}
            
            pushd "${rootModule}" || exit
            
            if [ ! -f ".terraform.lock.hcl" ]; then
              echo "Terraform lockfile doesn't exist in the root module ${rootModule}. Please create one using \"terraform init -backend=false\""
              exit 1
            fi
            
            terraform init -backend=false
            terraform validate
            
            popd || exit
          done;
  format:
    name: "format"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # Checks that all Terraform configuration files adhere to a canonical format
      - name: Terraform Format
        run: terraform fmt -check -recursive

  tfsec:
    name: "tf-sec"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Run tfsec with reviewdog
        uses: reviewdog/action-tfsec@v1.17.0
        if: ${{ always() }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_error: "true"
          filter_mode: "nofilter"
            #tfsec_flags: "-e general-secrets-sensitive-in-variable,general-secrets-sensitive-in-local,general-secrets-sensitive-in-attribute"
  
  tflint:
    name: "tf-lint"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Run tflint with reviewdog
        uses: reviewdog/action-tflint@v1.23.0
        if: ${{ always() }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_error: "true"
          filter_mode: "nofilter"
